name: ubuntu-latest

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install clang-18 lld-18 mingw-w64 cmake meson

    - name: Build SDK
      run: |
        make install
        ./libcxx.sh
        cd ${{ runner.tool_cache }}
        zip -r $GITHUB_WORKSPACE/ps5-payload-sdk.zip ps5-payload-sdk
        cd -
      env:
        DESTDIR: ${{ runner.tool_cache }}/ps5-payload-sdk
        PS5_PAYLOAD_SDK: ${{ runner.tool_cache }}/ps5-payload-sdk
        WIN: 1

    - name: Bundle SDK
      run: |
        cd ${{ runner.tool_cache }}
        zip -r $GITHUB_WORKSPACE/ps5-payload-sdk.zip ps5-payload-sdk
        cd -

    - name: Build samples
      run: |
        source $PS5_PAYLOAD_SDK/toolchain/prospero.sh
        $MAKE -C samples/arbitrary_syscall
        $MAKE -C samples/browser
        $MAKE -C samples/hello_cxx
        $MAKE -C samples/hello_cxx23
        $MAKE -C samples/hello_dlfcn
        $MAKE -C samples/hello_kenv
        $MAKE -C samples/hello_sprx
        $MAKE -C samples/hello_stdio
        $MAKE -C samples/hello_world
        $MAKE -C samples/hwinfo
        $MAKE -C samples/list_files
        $MAKE -C samples/mntinfo
        $MAKE -C samples/notify
        $MAKE -C samples/notify_debug
        $MAKE -C samples/ps
        $CMAKE -S samples/hello_cmake -B samples/hello_cmake/build
        $CMAKE --build samples/hello_cmake/build
        $MESON setup samples/hello_meson samples/hello_meson/build
        $MESON compile -C samples/hello_meson/build
      env:
          PS5_PAYLOAD_SDK: ${{ runner.tool_cache }}/ps5-payload-sdk

    - name: Upload SDK
      uses: actions/upload-artifact@v4
      with:
        name: SDK
        include-hidden-files: true
        path: ./ps5-payload-sdk.zip
        if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write

    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: SDK
          path: .

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: ps5-payload-sdk.zip
